baseurl = "https://be-net.github.io/2016"
languageCode = "en-us"
title = "Belgian Network Research Meeting"
theme = "lithium"
googleAnalytics = ""
disqusShortname = ""
publishdir = "docs"

[permalinks]
    post = "/:year/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Program"
    url = "/program/"
    weight = -106
[[menu.main]]
    name = "Registration"
    url = "/registration/"
    weight = -105
[[menu.main]]
    name = "Location"
    url = "/location-and-contact/"
    weight = -104

[params]
    titleshort = "BeNet2016"
    description = "Bla bla bla"

    [params.logo]
      url = "logo.png"
      width = 50
      height = 50

