baseurl = "https://be-net.github.io/2016/"
languageCode = "en-us"
title = "Belgian Network Research Meeting"
theme = "lithium"
googleAnalytics = ""
disqusShortname = ""
publishdir = "docs"
ignoreFiles = [ "\\.bak$" ]

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[permalinks]
    post = "/:year/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Program"
    url = "/program/"
    weight = -106
[[menu.main]]
    name = "Registration"
    url = "/registration/"
    weight = -105
[[menu.main]]
    name = "Location"
    url = "/location-and-contact/"
    weight = -104

[params]
  titleshort = "BeNet2016"
  description = "Belgian Network Research Meeting"
  abs_deadline = "2016-10-31"
  reg_deadline = "2016-11-20"
  not_deadline = "2016-11-15"

  [params.logo]
    url = "logo.png"
    width = 50
    height = 50
